Update run_proxy.yml

diff --git a/.github/workflows/run_proxy.yml b/.github/workflows/run_proxy.yml
--- a/.github/workflows/run_proxy.yml
+++ b/.github/workflows/run_proxy.yml
@@ -58,11 +58,11 @@ jobs:
 
           export NETBIRD_UP_CMD="PIONS_LOG_DEBUG=all NB_LOG_LEVEL=debug GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info netbird up  --setup-key $NETBIRD_KEY"
           if ! sh -c "$NETBIRD_UP_CMD"; then     
-          echo "NETBIRD_UP fail with exit code: $?"    
-          netbird status -d --filter-by-status connected
-          if [ $? -ne 0 ]; then
-          echo "netbird status failed with exit code: $?"
-          fi
+            echo "NETBIRD_UP fail with exit code: $?"
+            netbird status -d --filter-by-status connected
+            if [ $? -ne 0 ]; then
+              echo "netbird status failed with exit code: $?"
+            fi
           fi
           
           # netbird status 
